/* Generated by dbus-binding-tool; do not edit! */

#include <glib.h>
#include <dbus/dbus-glib.h>

G_BEGIN_DECLS

#ifndef DBUS_GLIB_CLIENT_WRAPPERS_nl_commserv_interface
#define DBUS_GLIB_CLIENT_WRAPPERS_nl_commserv_interface

static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wlm_test (DBusGProxy *proxy, const gint IN_test_param, const GArray* IN_input_string, GError **error)

{
  return dbus_g_proxy_call (proxy, "wlm_test", error, G_TYPE_INT, IN_test_param, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_string, G_TYPE_INVALID, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wlm_test_reply) (DBusGProxy *proxy, GError *error, gpointer userdata);

static void
nl_commserv_interface_wlm_test_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INVALID);
  (*(nl_commserv_interface_wlm_test_reply)data->cb) (proxy, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wlm_test_async (DBusGProxy *proxy, const gint IN_test_param, const GArray* IN_input_string, nl_commserv_interface_wlm_test_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wlm_test", nl_commserv_interface_wlm_test_async_callback, stuff, g_free, G_TYPE_INT, IN_test_param, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_string, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wlm_function (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, GArray** OUT_output_data, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wlm_function", error, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), OUT_output_data, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wlm_function_reply) (DBusGProxy *proxy, GArray *OUT_output_data, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wlm_function_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  GArray* OUT_output_data;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), &OUT_output_data, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wlm_function_reply)data->cb) (proxy, OUT_output_data, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wlm_function_async (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, nl_commserv_interface_wlm_function_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wlm_function", nl_commserv_interface_wlm_function_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wlm_gsmmux (DBusGProxy *proxy, const gint IN_function_no, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wlm_gsmmux", error, G_TYPE_INT, IN_function_no, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wlm_gsmmux_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wlm_gsmmux_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wlm_gsmmux_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wlm_gsmmux_async (DBusGProxy *proxy, const gint IN_function_no, nl_commserv_interface_wlm_gsmmux_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wlm_gsmmux", nl_commserv_interface_wlm_gsmmux_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_mux_flag (DBusGProxy *proxy, const gint IN_function_no, const gint IN_MuxFlag, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "mux_flag", error, G_TYPE_INT, IN_function_no, G_TYPE_INT, IN_MuxFlag, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_mux_flag_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_mux_flag_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_mux_flag_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_mux_flag_async (DBusGProxy *proxy, const gint IN_function_no, const gint IN_MuxFlag, nl_commserv_interface_mux_flag_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "mux_flag", nl_commserv_interface_mux_flag_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, G_TYPE_INT, IN_MuxFlag, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wifi_general_function (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, GArray** OUT_output_data, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wifi_general_function", error, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), OUT_output_data, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wifi_general_function_reply) (DBusGProxy *proxy, GArray *OUT_output_data, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wifi_general_function_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  GArray* OUT_output_data;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), &OUT_output_data, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wifi_general_function_reply)data->cb) (proxy, OUT_output_data, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wifi_general_function_async (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, nl_commserv_interface_wifi_general_function_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wifi_general_function", nl_commserv_interface_wifi_general_function_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wifi_status (DBusGProxy *proxy, const gint IN_function_no, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wifi_status", error, G_TYPE_INT, IN_function_no, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wifi_status_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wifi_status_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wifi_status_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wifi_status_async (DBusGProxy *proxy, const gint IN_function_no, nl_commserv_interface_wifi_status_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wifi_status", nl_commserv_interface_wifi_status_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wifi_connect (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wifi_connect", error, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wifi_connect_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wifi_connect_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wifi_connect_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wifi_connect_async (DBusGProxy *proxy, const gint IN_function_no, const GArray* IN_input_data, nl_commserv_interface_wifi_connect_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wifi_connect", nl_commserv_interface_wifi_connect_async_callback, stuff, g_free, G_TYPE_INT, IN_function_no, dbus_g_type_get_collection ("GArray", G_TYPE_UCHAR), IN_input_data, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wifi_enable (DBusGProxy *proxy, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wifi_enable", error, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wifi_enable_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wifi_enable_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wifi_enable_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wifi_enable_async (DBusGProxy *proxy, nl_commserv_interface_wifi_enable_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wifi_enable", nl_commserv_interface_wifi_enable_async_callback, stuff, g_free, G_TYPE_INVALID);
}
static
#ifdef G_HAVE_INLINE
inline
#endif
gboolean
nl_commserv_interface_wifi_disable (DBusGProxy *proxy, gint* OUT_return_value, GError **error)

{
  return dbus_g_proxy_call (proxy, "wifi_disable", error, G_TYPE_INVALID, G_TYPE_INT, OUT_return_value, G_TYPE_INVALID);
}

typedef void (*nl_commserv_interface_wifi_disable_reply) (DBusGProxy *proxy, gint OUT_return_value, GError *error, gpointer userdata);

static void
nl_commserv_interface_wifi_disable_async_callback (DBusGProxy *proxy, DBusGProxyCall *call, void *user_data)
{
  DBusGAsyncData *data = (DBusGAsyncData*) user_data;
  GError *error = NULL;
  gint OUT_return_value;
  dbus_g_proxy_end_call (proxy, call, &error, G_TYPE_INT, &OUT_return_value, G_TYPE_INVALID);
  (*(nl_commserv_interface_wifi_disable_reply)data->cb) (proxy, OUT_return_value, error, data->userdata);
  return;
}

static
#ifdef G_HAVE_INLINE
inline
#endif
DBusGProxyCall*
nl_commserv_interface_wifi_disable_async (DBusGProxy *proxy, nl_commserv_interface_wifi_disable_reply callback, gpointer userdata)

{
  DBusGAsyncData *stuff;
  stuff = g_new (DBusGAsyncData, 1);
  stuff->cb = G_CALLBACK (callback);
  stuff->userdata = userdata;
  return dbus_g_proxy_begin_call (proxy, "wifi_disable", nl_commserv_interface_wifi_disable_async_callback, stuff, g_free, G_TYPE_INVALID);
}
#endif /* defined DBUS_GLIB_CLIENT_WRAPPERS_nl_commserv_interface */

G_END_DECLS
